### PR TITLE
Fix listing of example directory

### LINKED ISSUE #5: [BUG] transitstacks.io.example_dir() loops over non-existent dir
## Describe the bug

When calling this method with a non-existent directory name, the code attempts to loop over that directory to build a list of available examples. It should instead loop over the root of the examples directory.

## To Reproduce

See the [Run output](https://github.com/cal-itp/Transitstacks/runs/2889774795?check_suite_focus=true#step:8:60) from the [`Python package` GitHub Action](https://github.com/cal-itp/Transitstacks/blob/main/.github/workflows/test.yml)

### Failing tests

- [x] [`tests/test_basic.py:test_csv_io()`](https://github.com/cal-itp/Transitstacks/blob/main/tests/test_basic.py#L25)

### Triggering line of code

[`transitstacks/io.py:139`](https://github.com/cal-itp/Transitstacks/blob/main/transitstacks/io.py#L139):

```python
def example_dir(example_name: str):
    """Takes an example name and returns the directory.

    Args:
        example_name: name of example
    """
    
    package_dir = os.path.dirname(os.path.abspath(__file__))
    main_example_dir = os.path.join(os.path.dirname(package_dir), "examples")

    example_dir = os.path.join(main_example_dir, example_name)
    
    if not os.path.exists(example_dir):
        available_examples = [
            name for name in os.listdir(example_dir) if os.path.isdir(name)  #<---- error here
        ]
```

### Thoughts on resolution

```python
def example_dir(example_name: str):
    """Takes an example name and returns the directory.

    Args:
        example_name: name of example
    """
    
    package_dir = os.path.dirname(os.path.abspath(__file__))
    main_example_dir = os.path.join(os.path.dirname(package_dir), "examples")

    example_dir = os.path.join(main_example_dir, example_name)
    
    if not os.path.exists(example_dir):
        available_examples = [
            name for name in os.listdir(main_example_dir) if os.path.isdir(name)  #<---- os.listdir(main_example_dir)
        ]
```

### PR DESCRIPTION
**Pull request by thekaveman**
# New Pull Request

## What existing problem does the pull request solve and why should we include it?

By the time this line executes, we've already determined `example_dir` does not exist, so there is no sense in trying to list it.

Instead, list the parent directory `main_example_dir`, which (presumably) contains some specific example directories.

## What is the testing plan?

*Demonstrate the code is solid by discussing how results are verified and covered by tests.*

- [X] Code for this PR is covered in tests
- [ ] Code passes all existing tests
- [X] Code is attempting to make existing tests pass

## Code formatting

*Code should be PEP8 compliant before merging by running a package like [`black`](https://pypi.org/project/black/)*

- [X] Code linted

## Applicable Issues

*Please do not create a Pull Request without creating an issue first.*

### Issues List

Closes #5

### CODE REVIEW

**Comment by e-lo** [comment]
@thekaveman  - wondering why the pre-commit checks didn't bomb on my local commit, [but are in GH Actions](https://github.com/cal-itp/Transitstacks/pull/6/checks?check_run_id=2946208828)? Is there something in the setup that is causing it to skip locally?

**Comment by thekaveman** [comment]
@e-lo I'm not sure? I pulled your commit in and ran `pre-commit run --all --all-files` and it bombed the same way.

I also tried renaming the `.csv` files to get rid of spaces etc. and when I committed that change, `pre-commit` also complained. Besides the line-endings/extra spaces/etc. there's some funky metadata or something at the top of alot of these files - is that correct?

E.g. first row from `components.csv` looks like a description or something?

```csv
Key: pcc_id, a concatenation of Product, Component, and Contract ID.
A many-to-one relationship with contracts using the foreign key: Contract ID",,,,,,,,,
pcc_id,Product,Component,Contract ID,Transit Provider,Vendor,~Capital Service Entry Date,~Capital EOL Date,Notes,Version
Token Transit Mobile Ticketing|Mobile ticketing|Token Transit|GET Bus 1,Token Transit Mobile Ticketing,Mobile ticketing,GET Bus 1,GET Bus,Token Transit,,,,
TO CONFIRM|Farebox|Genfare|GET Bus 2,TO CONFIRM,Farebox,GET Bus 2,GET Bus,Genfare,,,,
```

Can I clean that content up as well?

**Comment by e-lo** [comment]
> first row from components.csv looks like a description or something?

Yeah - it is a direct download from the transit stacks google sheet.  But...for the purposes of this repo I think we should just assume pure csv (more consistent with getting it on GCS anyway).

**Comment by thekaveman** [comment]
It looks like tests are now passing @e-lo! (And `pre-commit` checks)

I'll take a look at #7 / the missing `/icons` next. I think this is good to merge since we fixed the initial bug with  `transitstacks.io.example_dir()` and got the examples directory back in there.

**Pull request closed without merging**
